### ISSUE TITLE
Change Keycode to use integer instead of mapping to a virual key

### ISSUE THREAD

**Issue by edwin0cheng** [edwin0cheng/unrust#32]
It is related to commit https://github.com/edwin0cheng/unrust/commit/726e14f3080c61427652aeea87c61bf0604fef62

It seem like the keyboard not only keyboard layout dependents, and it is OS depenents:
https://www.berrange.com/posts/2010/07/04/a-summary-of-scan-code-key-codes-sets-used-in-the-pc-virtualization-stack/

Maybe we should use integer from upstream library instead of remapping it ?

@jice-nospam

**Comment by jice-nospam** [comment]
https://i.stack.imgur.com/LD8pT.png

**Comment by jice-nospam** [comment]
I'm working on a fix using this macos table

**Comment by edwin0cheng** [comment]
Um....Seem like i misunderstanding something. Would you mind to explain this [code](https://github.com/edwin0cheng/unrust/commit/0fc725ef4aeca827b51aa629b94d82e6099e8a4b#diff-ccaae27a483b73e514b4d5417220815aR160) to me ?
Where do you find this mapping ?

Im using this : http://keycode.info/ to test my keycode , for example , my `a` key map to 65, w hich map to 0x41.

**Comment by edwin0cheng** [comment]
So that would you mind test it in your non qwerty keyboard ?

**Comment by jice-nospam** [comment]
http://keycode.info/  displays the virtual key codes. I also get 65 for A because they're the same everywhere.
What we need is scancodes. I used [this table](https://msdn.microsoft.com/en-us/library/aa299374(v=vs.60).aspx) to write the Windows code. On windows A is scancode 30 (0x1E) on a qwerty keyboard. And I get the same scancode when I press Q on my azerty keyboard. This is what you need for WSAD key control.

According to [this diagram](https://i.stack.imgur.com/LD8pT.png), A scancode for mac is 0x00.
Let me try and write a macos mapping table, we'll see if it works for you

**Comment by edwin0cheng** [comment]
Okay i understand now so i misunderstand Keycode and Scancode. Lets wait for you pull request and let me test it 👍

**Comment by edwin0cheng** [comment]
Fixed by https://github.com/edwin0cheng/unrust/pull/33
